trigger:
  branches:
    include:
     - '*'

pool: local #Locally run agent

# variables:
#   customTag: '' #Init

steps:
# - script: |
#     customTag="$(Build.BuildId)";
#     echo "##vso[build.updatebuildnumber]$customTag"
#     echo "##vso[task.setvariable variable=customTag]$customTag"
#   displayName: 'Set Custom Build Tag'

#Build dotnet
#Build Dockerimage
#Scan with Trivy
#Upload to ECR
#Make that Dockerimage run on EC2 instance

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '6.0.x'
    installationPath: $(Agent.ToolsDirectory)/dotnet
  displayName: 'Install .NET SDK'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
  displayName: 'Restore Packages'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    arguments: '--configuration Release'
  displayName: 'Build Project'