trigger:
  branches:
    include:
     - '*'

pool: local #Locally run agent

#Install Dotnet SDK to Agent
#Restore Dotnet nuget packages
#Build Dotnet solution
#Build Docker Image
#Install Trivy
#Scan Docker Image with Trivy
#Upload Docker Image to Amazon ECR
#Make that Dockerimage run on EC2 instance

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '6.0.x'
    installationPath: $(Agent.ToolsDirectory)/dotnet
  displayName: 'Install .NET SDK'

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '*.sln'
  displayName: 'Restore Packages'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '*.sln'
    arguments: '--configuration Release'
  displayName: 'Build Solution'

- script: |
    docker build -f SampleDockerCRUDApp/Dockerfile -t sampledockercrudapp:$(Build.BuildNumber) .
  displayName: 'Build Docker Image'

- script: |
    docker pull aquasec/trivy:latest

    docker run --rm -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy:latest --quiet sampledockercrudapp:$(Build.BuildNumber)
  displayName: 'Pull Trivy from Docker and Scan the Dockerfile'