trigger:
  branches:
    include:
     - '*'

pool: local #Locally run agent

#Install Dotnet SDK to Agent
#Restore Dotnet nuget packages
#Build Dotnet solution
#Build Docker Image
#Pull Trivy from Dockerhub and Scan built Docker Image with it
#Authenticate to Amazon ECR
#Tag Docker Image
#Upload Tagged Docker Image to Amazon ECR

variables:
  AWS_ACCESS_KEY_ID: $(awsAccessKeyId)
  AWS_SECRET_ACCESS_KEY: $(awsSecretKey)
  AWS_DEFAULT_REGION: $(awsRegion)
  ECR_REPO_URL: $(awsEcrUri)

jobs:
  - job: Build
    displayName: 'Restore & Build'
    steps:
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '6.0.x'
        installationPath: $(Agent.ToolsDirectory)/dotnet
      displayName: 'Install .NET SDK'

    - task: DotNetCoreCLI@2
      inputs:
        command: 'restore'
        projects: '*.sln'
      displayName: 'Restore Packages'

    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
        projects: '*.sln'
        arguments: '--configuration Release'
      displayName: 'Build Solution'

    - script: |
        docker build -f SampleDockerCRUDApp/Dockerfile -t sampledockercrudapp:$(Build.BuildNumber) .
      displayName: 'Build Docker Image'

  - job: Trivy
    displayName: 'Tests'
    dependsOn: Build
    steps:
    - script: |
        docker pull aquasec/trivy:latest
        docker run --rm -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy:latest --quiet image sampledockercrudapp:$(Build.BuildNumber)
      displayName: 'Pull Trivy from Docker and Scan the Dockerfile'

  - job: DeployToECR
    dependsOn: Build
    displayName: 'Deploy Docker Image to AWS'
    steps:
    - script: |
        aws ecr get-login-password --region $(AWS_DEFAULT_REGION) | docker login --username AWS --password-stdin $(ECR_REPO_URL)
      displayName: 'Login to Amazon ECR'

    - script: |
        docker tag sampledockercrudapp:$(Build.BuildNumber) $(ECR_REPO_URL):$(Build.BuildNumber)
      displayName: 'Tag Docker Image'

    - script: |
        docker push $(ECR_REPO_URL):$(Build.BuildNumber)
      displayName: 'Push Docker Image to ECR'

  - job: RunImageOnEC2
    dependsOn: DeployToECR
    displayName: 'Run Docker Image from ECR to EC2'
    steps:

    - task : DownloadSecureFile@1
      inputs:
        secureFile: 'lg-kp-1.pem'

    - script: |
        chmod 600 $(Agent.TempDirectory)/lg-kp-1.pem
        ssh -o StrictHostKeyChecking=no -i $(Agent.TempDirectory)/lg-kp-1.pem ec2-user@34.229.192.186 "
        $(aws ecr get-login --no-include-email --region $(AWS_DEFAULT_REGION)) && \
        docker pull $(ECR_REPO_URL):$(Build.BuildNumber) && \
        docker run $(ECR_REPO_URL):$(Build.BuildNumber)
        "
      displayName: 'SSH into EC2 instance and Pull&Run Docker Image from ECR'
          
