trigger:
  branches:
    include:
     - '*'

pool: local #Locally run agent

#Install Dotnet SDK to Agent
#Restore Dotnet nuget packages
#Build Dotnet solution
#Build Docker Image
#Pull Trivy from Dockerhub and Scan built Docker Image with it
#Upload Docker Image to Amazon ECR
#Make that Dockerimage run on EC2 instance

variables:
  AWS_ACCESS_KEY_ID: $(awsAccessKeyId)
  AWS_SECRET_ACCESS_KEY: $(awsSecretKey)
  AWS_REGION: $(awsRegion)
  AWS_ECR_URI: $(awsEcrUri)

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '6.0.x'
    installationPath: $(Agent.ToolsDirectory)/dotnet
  displayName: 'Install .NET SDK'

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '*.sln'
  displayName: 'Restore Packages'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '*.sln'
    arguments: '--configuration Release'
  displayName: 'Build Solution'

- script: |
    docker build -f SampleDockerCRUDApp/Dockerfile -t sampledockercrudapp:$(Build.BuildNumber) .
  displayName: 'Build Docker Image'

- script: |
    docker pull aquasec/trivy:latest
    docker run --rm -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy:latest --quiet image sampledockercrudapp:$(Build.BuildNumber)
  displayName: 'Pull Trivy from Docker and Scan the Dockerfile'

- script: |
    aws --version
    docker login -u AWS -p $(aws ecr get-login-password --region $(AWS_REGION)) $(AWS_ECR_URI)
  displayName: 'Login to Amazon ECR'

- script: |
    docker tag sampledockercrudapp:$(Build.BuildNumber):latest $(AWS_ECR_URI):latest
  displayName: 'Tag Docker Image'

- script: |
    docker push $(AWS_ECR_URI):latest
  displayName: 'Push Docker Image to ECR'
